apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  #namespace: icgroup
  labels:
    env: prod
    type: local
    app: odoo
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /data-odoo
