apiVersion: v1
kind: Secret
metadata:
  name: odoo-secret
  labels:
    env: prod
    app: odoo
type: Opaque
data:
  # echo "myodoo" -n | base64
  password: bXlvZG9vIC1uCg==
  # echo "odoo" -n | base64
  user: b2RvbyAtbgo=

