apiVersion: v1
kind: ConfigMap
metadata:
  name: ic-webapp-cm
  #namespace: icgroup
  labels:
    env: prod
    app: ic-webapp
data:
  ODOO_URL: http://10.211.55.60:30010
  PGADMIN_URL: http://10.211.55.60:30011