apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: icgroup
  labels:
    env: prod 
    app: postgress
spec:
  selector:
    app: postgress
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
