apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  #namespace: icgroup
  labels:
    env: prod
    app: postgress
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
hostPath:
  path: /data-postgres
